site_name: Cleanroom Encyclopedia
repo_url: https://github.com/CleanroomMC/Encyclopedia
repo_name: CleanroomMC/Encyclopedia

nav:
  - Home: index.md
  - About: about.md
  - Mod Development:
    - Debugging: mod-development/debugging.md
    - Sidedness: mod-development/sidedness.md
    - Behaviour:
      - Neighbours: mod-development/behaviour/neighbours.md
    - Event:
      - Overview: mod-development/event/overview.md
      - PlayerDestroyItemEvent: mod-development/event/player-destroy-item-event.md
    - Game Object:
      - Sound:
        - Play Sound: mod-development/game-object/sound/play.md
    - Mixin:
      - Preface: mod-development/mixin/preface.md
      - MixinBooter: mod-development/mixin/mixinbooter.md
      - Annotation:
        - "@Shadow": mod-development/mixin/annotation/shadow.md
      - Environment:
        - Registration: mod-development/mixin/environment/registration.md
        - Configuration: mod-development/mixin/environment/configuration.md
    - Rendering:
      - Colouring Blocks and Items: mod-development/rendering/colouring-blocks-and-items.md
  - Mod Wikis:
      - ModularUI:
          - Intro: mod-wiki/modularui/intro.md
          - Getting Started: mod-wiki/modularui/getting_started.md
          - Client GUI tutorial: mod-wiki/modularui/client_gui_tutorial.md
          - Synced GUI tutorial: mod-wiki/modularui/synced_gui_tutorial.md
          - Sizing and Positioning: mod-wiki/modularui/sizing_and_positioning.md
          - Framework: mod-wiki/modularui/framework.md
  - Proposal:
    - Standard:
      - Minecraft Technical Metric System: proposal/standard/mtms.md

theme:
  name: material
  custom_dir: theme
  language: en
  logo: assets/icon.png
  favicon: assets/icon.png
  font:
    text: Ubuntu
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
  features:
    - header.autohide
    - announce.dismiss
    - search.highlight
    - search.share

plugins:
  - search

markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      url_download: true

# extra:
#    alternate:
#      - name: English
#        link: /en/
#        lang: en
#      - name: 繁體中文
#        link: /tw/
#        lang: zh-TW
#     - name: 简体中文
#       link: /cn/
#       lang: zh